---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - args:
        - "--context=git://github.com/rahulmlokurte/devops-stuff/kubernetes/kubernetes-kaniko"
        - "--destination=rahulmlokurte/kaniko-test-image:1.0"
      image: "gcr.io/kaniko-project/executor:latest"
      name: kaniko
      volumeMounts:
        - mountPath: /kaniko/.docker
          name: kaniko-secret
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        items:
          - key: .dockerconfigjson
            path: config.json
        secretName: dockercred
